databases:
  - name: defaultdb
    plan: free
    databaseName: defaultdb
    user: avnadmin

services:
  - type: web
    plan: free
    name: ast_ocean
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ast_ocean.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: pg-ab41ed3-asmblxer.b.aivencloud.com
        fromDatabase:
          name: defaultdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4