# Generated by Django 5.1.1 on 2024-10-05 19:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_creaturecategories_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.creaturecategories')),
            ],
            options={
                'verbose_name_plural': 'Creatures',
            },
        ),
    ]
